name: Build and Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Create main zip package
        run: bun run zip

      - name: Create Firefox zip package
        run: bun run zip:firefox

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: extension-packages
          path: .output/*.zip
